apiVersion: v1
kind: Service
metadata:
  name: {{ template "cog.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.cog.serviceType }}
  ports:
  - name: api
    port: 4000
    targetPort: 4000
  - name: trigger-api
    port: 4001
    targetPort: 4001
  - name: service-api
    port: 4002
    targetPort: 4002
  - name: mqtt
    port: 1883
    targetPort: 1883
  selector:
    app: {{ template "cog.fullname" . }}
